### ISSUE TITLE
Add Option to Disable Foreign Key Checks in Delete Method

### ISSUE THREAD

**Issue by qadirpervez** [riao-project/riao-dbal#86]
**Description**
I would like to propose the addition of a new option in the delete method that allows users to disable foreign key checks. This can be particularly useful in scenarios where users want to delete records without enforcing foreign key constraints.

**Current Behavior**

```javascript
await maindb.query.delete({
  table: 'table1',
  where: {
    id: 1,
  },
});
```
>throws an error if you have a foreign key constraint

To disable this explicitly we need to do this:

```javascript

await maindb.driver.query({
  sql: 'SET FOREIGN_KEY_CHECKS = 0',
});

await maindb.query.delete({
  table: 'table1',
  where: {
    id: 1,
  },
});

await maindb.driver.query({
  sql: 'SET FOREIGN_KEY_CHECKS = 1',
});
```

**Suggested Behavior**

```javascript
await maindb.query.delete({
  table: 'table1',
  where: {
    id: 1,
  },
  options: {
    disableForeignKeyChecks: true // by default false
  }
});
```

**Comment by DrewImm** [comment]
I suggest using the explicit method of disabling/enabling FK checks before and after:

- This more closely matches standard SQL behavior https://stackoverflow.com/a/9912760
- Adding as an option may cause misuse/overuse; with developers using this as a work-around for not using or understanding FK relationships
- Often times when bypassing FK constraints, you may make multiple calls to delete from various tables/etc.; so it makes sense to disable FK checks before all deletions, and re-enabling after


However, I do think there should be helper method(s) to disable/enable FK checks without having to use raw SQL. Logged #88
